# Generated by Django 3.1.7 on 2021-03-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biaoge',
            fields=[
                ('xx', models.FloatField(help_text='经度')),
                ('yy', models.FloatField(help_text='纬度')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
