# Generated by Django 3.1.7 on 2021-03-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaoge',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='', help_text='Age', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='approaches',
            field=models.BooleanField(default=False, help_text='Approaches?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='chasing',
            field=models.BooleanField(default=False, help_text='Chasing?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='climbing',
            field=models.BooleanField(default=False, help_text='Climbing?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='date',
            field=models.DateField(default='', help_text='date'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='eating',
            field=models.BooleanField(default=False, help_text='Eating?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='foraging',
            field=models.BooleanField(default=False, help_text='Foraging?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='Indifferent?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='kuks',
            field=models.BooleanField(default=False, help_text='Kuks?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='moans',
            field=models.BooleanField(default=False, help_text='Moans'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='other_activities',
            field=models.CharField(help_text='Other Activities', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='primary_Fur_Color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='quaas',
            field=models.BooleanField(default=False, help_text='Quaas?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='running',
            field=models.BooleanField(default=False, help_text='Running?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='Runs From?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='', help_text='shift', max_length=50),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='specific_location',
            field=models.CharField(help_text='Specific Location', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text='Tail Flags?'),
        ),
        migrations.AddField(
            model_name='biaoge',
            name='tail_twitches',
            field=models.BooleanField(default=False, help_text='Tail Twitches?'),
        ),
    ]
