# Generated by Django 3.1.7 on 2021-03-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_remove_biaoge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaoge',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age', max_length=50, null=True),
        ),
    ]
