# Generated by Django 3.1.7 on 2021-03-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20210315_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaoge',
            name='Date',
            field=models.DateField(default='1111-11-11', help_text='date'),
        ),
    ]
