# Generated by Django 3.1.7 on 2021-03-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_biaoge_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biaoge',
            old_name='primary_Fur_Color',
            new_name='primary_fur_color',
        ),
    ]
