# Generated by Django 3.1.7 on 2021-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20210316_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biaoge',
            old_name='Date',
            new_name='date',
        ),
    ]
