# Generated by Django 3.1.7 on 2021-03-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0007_auto_20210316_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaoge',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture of pet', upload_to='profiles_images'),
        ),
    ]
