# Generated by Django 3.1.7 on 2021-03-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0008_biaoge_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='biaoge',
            name='have_image',
            field=models.BooleanField(default=False, help_text='if this squirrel has image, please check it on'),
        ),
    ]
