# Generated by Django 3.1.7 on 2021-03-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0009_biaoge_have_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaoge',
            name='other_activities',
            field=models.CharField(default='', help_text='Other Activities', max_length=50),
        ),
    ]
