# Generated by Django 3.1.7 on 2021-03-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0010_auto_20210318_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaoge',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture of pet', upload_to='img/'),
        ),
    ]
