# Generated by Django 3.1.7 on 2021-03-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0012_auto_20210319_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture of pet', upload_to='img/')),
            ],
        ),
    ]
