# Generated by Django 3.1.7 on 2021-03-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0013_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaoge',
            name='date',
            field=models.DateField(default='1111-11-11', help_text='date', null=True),
        ),
        migrations.AlterField(
            model_name='biaoge',
            name='other_activities',
            field=models.CharField(default='', help_text='Other Activities', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biaoge',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture of pet', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='biaoge',
            name='shift',
            field=models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], default='', help_text='shift', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biaoge',
            name='xx',
            field=models.FloatField(help_text='Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='biaoge',
            name='yy',
            field=models.FloatField(help_text='Longtitude', null=True),
        ),
    ]
