# Generated by Django 3.1.7 on 2021-03-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0014_auto_20210319_0435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='images',
        ),
    ]
