# Generated by Django 3.1.7 on 2021-03-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0015_auto_20210319_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biaoge',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture of pet', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture of pet', upload_to='image/'),
        ),
    ]
