# Generated by Django 3.1.7 on 2021-03-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0017_auto_20210319_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
